name: RSS Update

on:
  schedule:
  - cron: '19 23 * * *'

jobs:
  rss-update:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with: { ref: rss }
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests
    - name: Update RSS Feed
      run: |
        python ./user_orchestrator.py > ./log.txt
    - name: Commit Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "GHA: Update RSS Feeds"
        git push origin rss
